### ISSUE TITLE
Prioritize Nuxt in issue creation page

### ISSUE THREAD

**Issue by clarkdo** [cmty/feedback#21]
### What problem does this feature solve?

Nuxt is the hottest repository in Nuxt community, I suggest to put it into first and default selection in issue creation.

![image](https://user-images.githubusercontent.com/4312154/43064829-eff726f4-8e57-11e8-94c8-1d571479eb8c.png)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/meta">CMTY</a> community (<a href="https://cmty.app/meta/cmty/issues/c27">#c27</a>)</em></sub></div>

**Comment by gaetansenn** [comment]
Hello @clarkdo,

Nice feedback. I suggest to add a most popular group on top of the list.

cc: @benjamincanac  @Atinux

**Comment by Atinux** [comment]
Hey @clarkdo 

Actually we will create repo and group page so this form with all the repos won't exist anymore :)
