### ISSUE TITLE
Mixed Content Warnings

### ISSUE THREAD

**Issue by manniL** [cmty/feedback#22]
### Version

[v0.3.0](https://github.com/cmty/releases/tag/v0.3.0)

### Reproduction link

[https://cmty.app/nuxt/nuxt.js/issues/c7477](https://cmty.app/nuxt/nuxt.js/issues/c7477)

### Steps to reproduce

Look into the linked issue.
See mixed content warning

### What is expected ?

-

### What is actually happening?

-

### Additional comments?

I'd suggest a solution similar to GitHub. They re-upload all content to their servers to prevent mixed content warnings. Maybe you could even grab those links as the images are (mostly) x-posted on GitHub anyway :thinking: 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/meta">CMTY</a> community (<a href="https://cmty.app/meta/cmty/issues/c28">#c28</a>)</em></sub></div>

**Comment by Atinux** [comment]
Thanks @manniL, it's definitely something we will work on :)

**Comment by manniL** [comment]
Closing here as the project was sunset. ☺️
